// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Not a URI", Scope = "member", Target = "~M:WebDeployParametersToolkit.Utilities.WebConfigSettingsReader.ReadApplicationSettings(System.Xml.XmlNode,System.Boolean,System.Boolean,WebDeployParametersToolkit.ParametersGenerationStyle)~System.Collections.Generic.IEnumerable{WebDeployParametersToolkit.Utilities.WebConfigSetting}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Not a URI", Scope = "member", Target = "~M:WebDeployParametersToolkit.Utilities.WebConfigSettingsReader.ReadCompilationDebugSettings(System.Xml.XmlNode,WebDeployParametersToolkit.ParametersGenerationStyle)~WebDeployParametersToolkit.Utilities.WebConfigSetting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Not a URI", Scope = "member", Target = "~M:WebDeployParametersToolkit.Utilities.WebConfigSettingsReader.ReadSessionStateSettings(System.Xml.XmlNode,WebDeployParametersToolkit.ParametersGenerationStyle)~System.Collections.Generic.IEnumerable{WebDeployParametersToolkit.Utilities.WebConfigSetting}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Not a URI", Scope = "member", Target = "~M:WebDeployParametersToolkit.Utilities.WebConfigSettingsReader.ReadMailSettings(System.Xml.XmlNode,WebDeployParametersToolkit.ParametersGenerationStyle)~System.Collections.Generic.IEnumerable{WebDeployParametersToolkit.Utilities.WebConfigSetting}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0006:Use foreach", Justification = "Using foreach results in object type instead of XmlNode", Scope = "member", Target = "~M:WebDeployParametersToolkit.Utilities.WebConfigSettingsReader.ReadApplicationSettings(System.Xml.XmlNode,System.Boolean,System.Boolean,WebDeployParametersToolkit.ParametersGenerationStyle)~System.Collections.Generic.IEnumerable{WebDeployParametersToolkit.Utilities.WebConfigSetting}")]
