// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.184
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebDeployParametersToolkit
{
    static class Vsix
    {
        public const string Id = "6435437e-72fb-4626-9a47-865f185ce258";
        public const string Name = "Web Deploy Parameters Toolkit";
        public const string Description = @"Tools to make it easy to work with parameters in Web Deploy (MSDeploy).  This includes automatically generating a Parameters.xml file from a web.config file, generating SetParameters.xml file from Parameters.xml";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Kyle Herzog";
        public const string Tags = "SetParameters, WebDeploy, MSDeploy, Parameters";
    }
}
