// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.182
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebDeployParametersToolkit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWebDeployParametersToolkitPackageString = "44ad5888-3abd-4031-b7fe-b9ed0c971969";
        public const string guidWebDeployParametersToolkitPackageCmdSetString = "b451bf5d-476a-43b7-8a00-11671601fdaa";
        public const string guidImagesString = "dc8edac2-f399-4700-bc21-e3638ee03a01";
        public const string guidImages1String = "98587af9-0198-4b19-80b3-7ffa3c51bb51";
        public const string guidImages2String = "7c3c774b-ce35-4dd9-882a-2419a415e699";
        public const string guidImages3String = "d5fc3208-e5eb-4e38-ad72-ee698a0671dc";
        public const string guidImages4String = "556b0e9f-c7c7-402a-a6e4-5a423bf87c5a";
        public static Guid guidWebDeployParametersToolkitPackage = new Guid(guidWebDeployParametersToolkitPackageString);
        public static Guid guidWebDeployParametersToolkitPackageCmdSet = new Guid(guidWebDeployParametersToolkitPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
        public static Guid guidImages1 = new Guid(guidImages1String);
        public static Guid guidImages2 = new Guid(guidImages2String);
        public static Guid guidImages3 = new Guid(guidImages3String);
        public static Guid guidImages4 = new Guid(guidImages4String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GenerateSetParametersCommandId = 0x0100;
        public const int cmdidNestCommand = 0x0101;
        public const int cmdidApplyMissingParametersCommand = 0x0102;
        public const int cmdidGenerateParametersCommand = 0x0103;
        public const int cmdidAddParameterizationTargetCommand = 0x0104;
        public const int GenerateSetParametersGlyph = 0x0001;
        public const int NestCommandGlyph = 0x0001;
        public const int ApplyMissingParametersGlyph = 0x0001;
        public const int GenerateParametersGlyph = 0x0001;
        public const int AddParameterizationTargetGlyph = 0x0001;
    }
}
